# Generated by Django 5.0.4 on 2024-05-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Joined_date',
            new_name='joined_date',
        ),
    ]
