# Generated by Django 5.0.4 on 2024-05-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_joined_date_member_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
    ]
